FROM node:20

# 1. Directorio de trabajo
WORKDIR /app

# 2. Copiamos solo package.json / lock primero (cache eficiente)
COPY package.json package-lock.json ./

# 3. Instalamos dependencias
RUN npm install

# 4. Copiamos el resto del código
COPY . .

# 5. Exponemos el puerto del dev server
EXPOSE 4200

# 6. Arrancamos Angular en modo desarrollo
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll=2000"]
