server {
    listen 80;
    server_name lavapp.net www.lavapp.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name lavapp.net www.lavapp.net;

    ssl_certificate /etc/letsencrypt/live/lavapp.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lavapp.net/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}