"""refactor wc + review model

Revision ID: 84beb084f9e4
Revises: b2c3d4e5f6a7
Create Date: 2026-03-23 12:12:56.993028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84beb084f9e4'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('felt_safe', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('accessible', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('has_toilet_paper', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('hygiene_products_available', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('could_enter_without_buying', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('has_gender_mixed_option', sa.Boolean(), nullable=False))
    op.drop_column('reviews', 'is_safe_space')
    op.drop_column('reviews', 'safety_rating')
    op.drop_column('reviews', 'safe_space_comment')
    op.add_column('wcs', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('wcs', 'has_intimate_hygiene_products')
    op.drop_column('wcs', 'gender_neutral')
    op.drop_column('wcs', 'only_for_customers')
    op.drop_column('wcs', 'accessible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wcs', sa.Column('accessible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('wcs', sa.Column('only_for_customers', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('wcs', sa.Column('gender_neutral', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('wcs', sa.Column('has_intimate_hygiene_products', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('wcs', 'is_public')
    op.add_column('reviews', sa.Column('safe_space_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('safety_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('is_safe_space', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'has_gender_mixed_option')
    op.drop_column('reviews', 'could_enter_without_buying')
    op.drop_column('reviews', 'hygiene_products_available')
    op.drop_column('reviews', 'has_toilet_paper')
    op.drop_column('reviews', 'accessible')
    op.drop_column('reviews', 'felt_safe')
    # ### end Alembic commands ###
