"""add wc customer_only and hygiene flags

Revision ID: bca5b10e44c8
Revises: 3b61ba01a708
Create Date: 2026-01-22 09:52:55.834791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca5b10e44c8'
down_revision: Union[str, Sequence[str], None] = '3b61ba01a708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wcs', sa.Column('only_for_customers', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('wcs', sa.Column('has_intimate_hygiene_products', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wcs', 'has_intimate_hygiene_products')
    op.drop_column('wcs', 'only_for_customers')
    # ### end Alembic commands ###
